# Generated by Django 4.1.5 on 2023-01-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensusChoropleth', '0005_geolevel_geography_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='char_name',
            field=models.CharField(max_length=200),
        ),
    ]
