# Generated by Django 4.1.5 on 2023-01-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensusChoropleth', '0006_alter_characteristic_char_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='geo_name',
            field=models.CharField(max_length=50),
        ),
    ]
