# Generated by Django 4.1.5 on 2023-01-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dguid', models.CharField(max_length=14)),
                ('geoname', models.CharField(max_length=25)),
                ('geolevel', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusChoropleth.characteristic')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CensusChoropleth.geography')),
            ],
        ),
    ]
