# Generated by Django 4.1.5 on 2023-01-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CensusChoropleth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geography',
            old_name='geolevel',
            new_name='geo_level',
        ),
        migrations.RenameField(
            model_name='geography',
            old_name='geoname',
            new_name='geo_name',
        ),
    ]
