# Generated by Django 4.1.5 on 2023-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensusChoropleth', '0003_alter_datum_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datum',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
