# Generated by Django 4.1.5 on 2023-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensusChoropleth', '0007_alter_geography_geo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='dguid',
            field=models.CharField(max_length=20),
        ),
    ]
